# Generated by Django 5.2.7 on 2025-11-02 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nivel', models.CharField(choices=[('T', 'Técnico'), ('P', 'Profesional')], default='P', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='AppWeb.sede')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['sede__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('EST', 'Estudiante'), ('DOC', 'Docente'), ('EMP', 'Empresa'), ('ADM', 'Administrador')], default='EST', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.TextField(help_text='Detalle completo del desafío o necesidad de la empresa')),
                ('sector', models.CharField(db_index=True, help_text='Ej: Logística, Energía, Retail, Salud, etc.', max_length=100)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, help_text='Ej: IA, logística, inventario, energía solar', max_length=255, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='PDF, Excel, imágenes, etc.', null=True, upload_to='solicitudes_empresas/')),
                ('estado', models.CharField(choices=[('REC', 'Recibida (pendiente de revisión)'), ('REV', 'En revisión por docente / comité'), ('APR', 'Aprobada internamente'), ('ASI', 'Asignada a estudiante(s)'), ('REJ', 'Rechazada'), ('FIN', 'Finalizada / cerrada')], db_index=True, default='REC', max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(limit_choices_to={'rol': 'EMP'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de empresa',
                'verbose_name_plural': 'Solicitudes de empresa',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sede',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('direccion_fiscal', models.CharField(max_length=255)),
                ('nif_cif', models.CharField(max_length=20, verbose_name='NIF/CIF')),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_contacto', models.EmailField(max_length=150)),
                ('documento_adjunto', models.FileField(blank=True, help_text='Documento de respaldo (PDF o Word).', null=True, upload_to='empresas/documentos/')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('REJ', 'Rechazada')], db_index=True, default='PEN', max_length=3)),
                ('email_tracking', models.EmailField(help_text='Correo que dejó el usuario para seguimiento.', max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Empresa',
                'verbose_name_plural': 'Registros de Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('resumen', models.TextField(help_text='Resumen ejecutivo', max_length=500)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('EST', 'Estudiantil'), ('DOC', 'Docente'), ('EMP', 'Empresarial')], db_index=True, max_length=3)),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('REV', 'En revisión'), ('APR', 'Aprobado'), ('ACT', 'En ejecución / Activo'), ('DET', 'Detenido / En pausa'), ('FIN', 'Finalizado'), ('PUB', 'Publicado'), ('ARC', 'Archivado')], db_index=True, default='BOR', max_length=3)),
                ('anio', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('es_publico', models.BooleanField(db_index=True, default=False)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='AppWeb.carrera')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='AppWeb.sede')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialProyectoParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LID', 'Líder del Proyecto / Scrum Master'), ('DEV', 'Desarrollador / Programador'), ('AI', 'Especialista en Inteligencia Artificial / Machine Learning'), ('DS', 'Científico/a de Datos'), ('UX', 'Diseñador UX/UI'), ('QA', 'Tester / Control de Calidad'), ('ANA', 'Analista de Negocios / Data Analyst'), ('PMO', 'Coordinador PMO / Gestión de Proyectos'), ('MKT', 'Especialista en Marketing Digital / Comercial'), ('FIN', 'Analista Financiero'), ('DOC', 'Docente Supervisor / Profesor Guía'), ('INV', 'Investigador / Innovación / I+D'), ('LOG', 'Especialista en Logística / Supply Chain'), ('IOT', 'Integrador IoT / Automatización Industrial')], max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_participantes', to='AppWeb.proyecto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Participación en Proyecto',
                'verbose_name_plural': 'Historial de Participaciones en Proyectos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrera',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=200, null=True)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('ACCESS', 'Acceso a página/módulo')], db_index=True, max_length=10)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Advertencia'), ('CRIT', 'Crítico')], db_index=True, default='INFO', max_length=10)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACE', 'Aceptado por docente'), ('PRO', 'En progreso (con estudiantes activos)'), ('FIN', 'Finalizado por docente'), ('CAN', 'Cancelado / Rechazado')], db_index=True, default='ACE', max_length=3)),
                ('comentarios_docente', models.TextField(blank=True, null=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='AppWeb.solicitudempresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('docente_responsable', models.ForeignKey(limit_choices_to={'rol': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados_como_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'EST'}, related_name='proyectos_asignados_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de proyecto',
                'verbose_name_plural': 'Asignaciones de proyectos',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudempresa',
            index=models.Index(fields=['estado', 'sector'], name='AppWeb_soli_estado_0528f3_idx'),
        ),
        migrations.AddIndex(
            model_name='registroempresa',
            index=models.Index(fields=['estado'], name='AppWeb_regi_estado_29c64f_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado', 'es_publico', 'anio'], name='AppWeb_proy_estado_547330_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['tipo', 'anio'], name='AppWeb_proy_tipo_f6c991_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('nombre', 'sede')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['accion', 'severidad', 'modelo'], name='AppWeb_audi_accion_71fb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['fecha_evento'], name='AppWeb_audi_fecha_e_1af2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionproyecto',
            index=models.Index(fields=['estado'], name='AppWeb_asig_estado_0accd8_idx'),
        ),
    ]
