# Generated by Django 5.2.7 on 2025-11-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroempresa',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
