# Generated by Django 5.2.7 on 2025-10-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_alter_usuario_options_usuario_rol_sede_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProyectoParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LID', 'Líder del Proyecto / Scrum Master'), ('DEV', 'Desarrollador / Programador'), ('AI', 'Especialista en Inteligencia Artificial / Machine Learning'), ('DS', 'Científico/a de Datos'), ('UX', 'Diseñador UX/UI'), ('QA', 'Tester / Control de Calidad'), ('ANA', 'Analista de Negocios / Data Analyst'), ('PMO', 'Coordinador PMO / Gestión de Proyectos'), ('MKT', 'Especialista en Marketing Digital / Comercial'), ('FIN', 'Analista Financiero'), ('DOC', 'Docente Supervisor / Profesor Guía'), ('INV', 'Investigador / Innovación / I+D'), ('LOG', 'Especialista en Logística / Supply Chain'), ('IOT', 'Integrador IoT / Automatización Industrial')], max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_participantes', to='AppWeb.proyecto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Participación en Proyecto',
                'verbose_name_plural': 'Historial de Participaciones en Proyectos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
