# Generated by Django 5.2.8 on 2025-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_alter_asignacionproyecto_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proyecto',
            name='AppWeb_proy_estado_547330_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='AppWeb_proy_tipo_f6c991_idx',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('Informática', 'Informática'), ('Mecánica', 'Mecánica'), ('Tecnología Aplicada', 'Tecnología Aplicada'), ('Logística', 'Logística'), ('Energía', 'Energía'), ('Administración', 'Administración'), ('Educación', 'Educación')], default='Informática', max_length=50),
        ),
    ]
