# Generated by Django 5.2.7 on 2025-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_historialproyectoparticipantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
