# Generated by Django 5.2.8 on 2025-11-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_remove_proyecto_appweb_proy_estado_547330_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LID', 'Líder del Proyecto'), ('DEV', 'Desarrollador'), ('DS', 'Científico de Datos'), ('AI', 'Especialista en IA/ML'), ('UX', 'Diseñador UX/UI'), ('QA', 'Tester / Control de Calidad'), ('ANA', 'Analista de Negocios'), ('DOC', 'Docente Guía'), ('INV', 'Investigador'), ('OTR', 'Otro')], default='DEV', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='AppWeb.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('proyecto', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', through='AppWeb.ParticipanteProyecto', to=settings.AUTH_USER_MODEL),
        ),
    ]
