# Generated by Django 5.2.7 on 2025-10-29 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_alter_proyecto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('metodo', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('status_code', models.PositiveIntegerField(db_index=True, default=200)),
                ('accion', models.CharField(choices=[('VIEW', 'Vista / Navegación'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('ERROR', 'Error / Excepción')], db_index=True, max_length=10)),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Advertencia'), ('CRIT', 'Crítica')], db_index=True, default='INFO', max_length=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('despues', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'accion', 'severidad'], name='AppWeb_audi_timesta_31e001_idx'), models.Index(fields=['path'], name='AppWeb_audi_path_b36025_idx'), models.Index(fields=['modelo', 'objeto_id'], name='AppWeb_audi_modelo_e434ed_idx'), models.Index(fields=['usuario', 'session_key'], name='AppWeb_audi_usuario_2d000a_idx')],
            },
        ),
    ]
