# Generated by Django 5.2.7 on 2025-10-29 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-fecha_evento'], 'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AppWeb_audi_timesta_31e001_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AppWeb_audi_path_b36025_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AppWeb_audi_modelo_e434ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AppWeb_audi_usuario_2d000a_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='antes',
            new_name='datos_antes',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='despues',
            new_name='datos_despues',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='payload',
            new_name='diff',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='ip',
            new_name='ip_origen',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='fecha_evento',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metodo_http',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('ACCESS', 'Acceso a página/módulo')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='severidad',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Advertencia'), ('CRIT', 'Crítico')], db_index=True, default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['accion', 'severidad', 'modelo'], name='AppWeb_audi_accion_71fb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['fecha_evento'], name='AppWeb_audi_fecha_e_1af2b9_idx'),
        ),
    ]
