# Generated by Django 5.2.8 on 2025-11-09 21:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_participanteproyecto_proyecto_participantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionproyecto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialproyectoparticipantes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participanteproyecto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registroempresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={},
        ),
        migrations.AlterModelOptions(
            name='solicitudempresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveIndex(
            model_name='asignacionproyecto',
            name='AppWeb_asig_estado_0accd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroempresa',
            name='AppWeb_regi_estado_29c64f_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitudempresa',
            name='AppWeb_soli_estado_0528f3_idx',
        ),
        migrations.RemoveField(
            model_name='historialproyectoparticipantes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historialproyectoparticipantes',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historialproyectoparticipantes',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='habilidades',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_est',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='docente_responsable',
            field=models.ForeignKey(limit_choices_to={'rol': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='estado',
            field=models.CharField(choices=[('ACE', 'Aceptado'), ('PRO', 'En progreso'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='ACE', max_length=3),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'EST'}, related_name='proyectos_asignados_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialproyectoparticipantes',
            name='rol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppWeb.carrera'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('Informática', 'Informática'), ('Mecánica', 'Mecánica'), ('Tecnología Aplicada', 'Tecnología Aplicada'), ('Logística', 'Logística'), ('Energía', 'Energía'), ('Administración', 'Administración'), ('Educación', 'Educación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('BOR', 'Borrador'), ('REV', 'En revisión'), ('APR', 'Aprobado'), ('ACT', 'En ejecución / Activo'), ('DET', 'Detenido / En pausa'), ('FIN', 'Finalizado'), ('PUB', 'Publicado'), ('ARC', 'Archivado')], default='BOR', max_length=3),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppWeb.sede'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('EST', 'Estudiantil'), ('DOC', 'Docente'), ('EMP', 'Empresarial')], max_length=3),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='email_tracking',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('REJ', 'Rechazada')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='nif_cif',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes_empresas/'),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='estado',
            field=models.CharField(choices=[('REC', 'Recibida'), ('REV', 'En revisión'), ('APR', 'Aprobada'), ('ASI', 'Asignada'), ('REJ', 'Rechazada'), ('FIN', 'Finalizada')], default='REC', max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
