# Generated by Django 5.2.8 on 2025-11-09 21:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0006_alter_asignacionproyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participanteproyecto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participanteproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='participanteproyecto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='participantes',
        ),
        migrations.AlterModelOptions(
            name='asignacionproyecto',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Asignación de proyecto', 'verbose_name_plural': 'Asignaciones de proyectos'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['sede__codigo', 'nombre'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='historialproyectoparticipantes',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Historial de Participación en Proyecto', 'verbose_name_plural': 'Historial de Participaciones en Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='registroempresa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registro de Empresa', 'verbose_name_plural': 'Registros de Empresas'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudempresa',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Solicitud de empresa', 'verbose_name_plural': 'Solicitudes de empresa'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='presupuesto_est',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='historialproyectoparticipantes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialproyectoparticipantes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historialproyectoparticipantes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='docente_responsable',
            field=models.ForeignKey(limit_choices_to={'rol': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados_como_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='estado',
            field=models.CharField(choices=[('ACE', 'Aceptado por docente'), ('PRO', 'En progreso (con estudiantes activos)'), ('FIN', 'Finalizado por docente'), ('CAN', 'Cancelado / Rechazado')], db_index=True, default='ACE', max_length=3),
        ),
        migrations.AlterField(
            model_name='asignacionproyecto',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'EST'}, related_name='proyectos_asignados_como_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialproyectoparticipantes',
            name='rol',
            field=models.CharField(choices=[('LID', 'Líder del Proyecto / Scrum Master'), ('DEV', 'Desarrollador / Programador'), ('AI', 'Especialista en Inteligencia Artificial / Machine Learning'), ('DS', 'Científico/a de Datos'), ('UX', 'Diseñador UX/UI'), ('QA', 'Tester / Control de Calidad'), ('ANA', 'Analista de Negocios / Data Analyst'), ('PMO', 'Coordinador PMO / Gestión de Proyectos'), ('MKT', 'Especialista en Marketing Digital / Comercial'), ('FIN', 'Analista Financiero'), ('DOC', 'Docente Supervisor / Profesor Guía'), ('INV', 'Investigador / Innovación / I+D'), ('LOG', 'Especialista en Logística / Supply Chain'), ('IOT', 'Integrador IoT / Automatización Industrial')], max_length=10),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='anio',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='AppWeb.carrera'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='es_publico',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('BOR', 'Borrador'), ('REV', 'En revisión'), ('APR', 'Aprobado'), ('ACT', 'En ejecución / Activo'), ('DET', 'Detenido / En pausa'), ('FIN', 'Finalizado'), ('PUB', 'Publicado'), ('ARC', 'Archivado')], db_index=True, default='BOR', max_length=3),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(help_text='Resumen ejecutivo', max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='AppWeb.sede'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('EST', 'Estudiantil'), ('DOC', 'Docente'), ('EMP', 'Empresarial')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='documento_adjunto',
            field=models.FileField(blank=True, help_text='Documento de respaldo (PDF o Word).', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='email_tracking',
            field=models.EmailField(help_text='Correo que dejó el usuario para seguimiento.', max_length=254),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('REJ', 'Rechazada')], db_index=True, default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='nif_cif',
            field=models.CharField(max_length=20, verbose_name='NIF/CIF'),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='PDF, Excel, imágenes, etc.', null=True, upload_to='solicitudes_empresas/'),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='descripcion',
            field=models.TextField(help_text='Detalle completo del desafío o necesidad de la empresa'),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='estado',
            field=models.CharField(choices=[('REC', 'Recibida (pendiente de revisión)'), ('REV', 'En revisión por docente / comité'), ('APR', 'Aprobada internamente'), ('ASI', 'Asignada a estudiante(s)'), ('REJ', 'Rechazada'), ('FIN', 'Finalizada / cerrada')], db_index=True, default='REC', max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='palabras_clave',
            field=models.CharField(blank=True, help_text='Ej: IA, logística, inventario, energía solar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='sector',
            field=models.CharField(db_index=True, help_text='Ej: Logística, Energía, Retail, Salud, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='titulo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='asignacionproyecto',
            index=models.Index(fields=['estado'], name='AppWeb_asig_estado_0accd8_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado', 'es_publico', 'anio'], name='AppWeb_proy_estado_547330_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['tipo', 'anio'], name='AppWeb_proy_tipo_f6c991_idx'),
        ),
        migrations.AddIndex(
            model_name='registroempresa',
            index=models.Index(fields=['estado'], name='AppWeb_regi_estado_29c64f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudempresa',
            index=models.Index(fields=['estado', 'sector'], name='AppWeb_soli_estado_0528f3_idx'),
        ),
        migrations.DeleteModel(
            name='ParticipanteProyecto',
        ),
    ]
