# Generated by Django 5.2.8 on 2025-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0007_alter_participanteproyecto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='experiencia',
            field=models.TextField(blank=True, null=True, verbose_name='Experiencia o descripción laboral'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='habilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades (separadas por comas)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='industrias_interes',
            field=models.TextField(blank=True, null=True, verbose_name='Industrias de interés (separadas por comas)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobre_mi',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre mí'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tecnologias_preferidas',
            field=models.TextField(blank=True, null=True, verbose_name='Tecnologías preferidas (separadas por comas)'),
        ),
    ]
