# Generated by Django 5.2.8 on 2025-11-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0008_usuario_experiencia_usuario_habilidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='AppWeb.carrera'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='AppWeb.sede'),
        ),
    ]
