# Generated by Django 5.2.7 on 2025-11-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0009_usuario_carrera_usuario_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.TextField(help_text='Resumen ejecutivo', max_length=700),
        ),
    ]
